apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin

        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "1"
            memory: 10000Mi
          requests:
            cpu: "1"
            memory: 8000Mi
        volumeMounts:
        - name: minio-pvc
          mountPath: /data
      volumes:
      - name: minio-pvc
        persistentVolumeClaim:
          claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
