apiVersion: batch/v1
kind: Job
metadata:
  name: check-results
  namespace: test
spec:
  template:
    spec:
      containers:
      - name: check-results
        image: dukegcb/calrissian:latest
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        command:
        - "sh"
        - "-c"
        - "more /calrissian/output-data/* | cat"
        volumeMounts:
        - mountPath: /calrissian/output-data
          name: calrissian-output-data
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: calrissian-output-data
        persistentVolumeClaim:
          claimName: calrissian-output-data